CREATE SCHEMA IF NOT EXISTS Product DEFAULT CHARACTER SET utf8;
USE Product;

CREATE TABLE IF NOT EXISTS Product
(
    id          BIGINT       NOT NULL AUTO_INCREMENT,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(100) NULL,
    created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1002;